# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import redirect.validators


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_auto_20180511_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='from_url',
            field=models.CharField(db_index=True, help_text="Absolute path, excluding the domain. Example: '/about/'", max_length=255, unique=True, validators=[redirect.validators.validate_regex], verbose_name='From URL'),
        ),
    ]
